BLACKLIST = [
    "absuelve",
    "justicia de arequipa",
    "fiscalia",
    "comisaria",
    "juzgado",
    "tribunal",
    "corte",
    "ministerio publico",
    "poder judicial",
    "sentencia",
    "apelacion",
    "recurso",
    "demanda",
    "corte suprema",
    "segunda instancia",
    "aceptar",
    "afirma",
    "procesales",
    "procesal",
    "justicia",
    "juez",
    "jueces",
    "superior",
    "superiores",
    "imaginante",
    "anonimo",
    "señora",
    "señor",
    "sr",
    "sra",
    "don",
    "dona",
    "AREQUIPA",
    "FUNDAMENTOS",
    "Delimitación",
    "corte",
    "ate",
    "RELATORÍA",
]
